apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: hp-kaas-frontier-ingress
    annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          if ($args ~ "^(?=.*(^|&)store=gnpt(&|$)).*") {
            rewrite ^/v2/search /gnpt/v3/search redirect;
          }
spec:
    ingressClassName: nginx
    rules:
        http:
            paths:
            - pathType: ImplementationSpecific
              path: /v2/search
              backend:
				service:
				  name: gnpt-service  # Update as per the service
				  port:
					number: 80
